blog/urls.py
from django.urls import path
from .views import PostDetailView, PostListView
app_name='blog'

urlpatterns = [
    path('post/', PostListView.as_view(), name='post_list'),  # Lista de publicaciones
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),  # Detalle de publicación
]

blog_personal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),  # Rutas de la app Blog
    path('', include('core.urls', namespace='core')),  # Rutas de la app Core
    path('ckeditor/upload/', ckeditor_views.upload, name='ckeditor_upload'),
    path('ckeditor/browse/', ckeditor_views.browse, name='ckeditor_browse'),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.timezone import now
from django.utils.text import slugify
from thumbnails.fields import ImageField
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.

class Post(models.Model):
    title = models.CharField('Titulo', max_length=200)
    slug = models.SlugField('Slug', unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    blog_image = ImageField('Portada del post',upload_to='post/images/', null=True, blank=True)
    content = RichTextField('Contenido')
    created_at = models.DateTimeField('Fecha de creación', default=now, editable=False)
    updated_at = models.DateTimeField('Fecha de actualización', auto_now=True)
    show_home = models.BooleanField('Mostrar en la home', default=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title) # Genera el slug a partir del título
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Publicacion'
        verbose_name_plural = 'Publicaciones'

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator


@method_decorator(login_required, name='dispatch')
class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'  # Nombre del template
    context_object_name = 'posts'  # Nombre con el que se accederán las publicaciones en la plantilla
    paginate_by = 3  # Número de publicaciones por página

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')

@method_decorator(login_required, name='dispatch')
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'  # Nombre del template para los detalles
    context_object_name = 'post'  # Nombre con el que se accederá a la publicación en la plantilla

    def get_queryset(self):
        return super().get_queryset().filter(slug=self.kwargs['slug']) #Para que machee por slug y no id

blog_personal/templates/blog/post_detail.html
{% extends "layout_base.html" %}


{% block head_title%} {{ post.title }} {% endblock %}

{% block page_content%}
<article id="{{ post.slug }}">
    <p>Fecha de publicacion: {{ post.created_at }}</p>
    <h1> {{ post.title }}</h1>
    {% if post.blog_image %}
        <picture>
            <img src="{{ post.blog_image.thumbnails.large.url }}">
        </picture>
        {% endif %}
    <div> {{ post.content|safe }}</div>
    <p><a href="{% url 'blog:post_list' %}">Volver a las noticias</a></p>
</article>
{% endblock %}

blog_personal/templates/blog/post_list.html
{% extends "layout_base.html" %}


{% block head_title%}Listado de noticias {% endblock %}

{% block page_content%}
    <h1>Descubre todas las noticias</h1>

    {% for post in posts %}
    <article id="{{ post.slug }}">
        <h2> {{ post.title }}</h2>
        <p>Fecha de publicacion: {{ post.created_at }}</p>
        <P>Autor: {{post.author}}</p>
        {% if post.blog_image %}
        <picture>
            <img src="{{ post.blog_image.thumbnails.small.url }}">
        </picture>
        {% endif %}
        <div> {{ post.content|truncatechars:500|safe }}...</div>
        <p><a href="{% url 'blog:post_detail' slug=post.slug %}">Ver noticia completa</a></p>
    </article>
    <br>
    <br>
    {% endfor %}
<!-- Creamos un bucle para que recorra cada campo de nuestro modelo y nos lo muestre en el html-->


<!-- Controles de paginación -->
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
            {% endif %}

            <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
            {% endif %}
        </span>
    </div>
{% endblock %}