blog/urls.py
from django.urls import path
from .views import PostDetailView, PostListView
app_name='blog'

urlpatterns = [
    path('post/', PostListView.as_view(), name='post_list'),  # Lista de publicaciones
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),  # Detalle de publicación
]

blog_personal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),  # Rutas de la app Blog
    path('', include('core.urls', namespace='core')),  # Rutas de la app Core
    path('ckeditor/upload/', ckeditor_views.upload, name='ckeditor_upload'),
    path('ckeditor/browse/', ckeditor_views.browse, name='ckeditor_browse'),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView, ContactoForm, RegisterView, LoginView, logout_view

app_name='core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactoForm.as_view(), name='contact' ),
    path('register/', RegisterView.as_view(), name='register' ),
    path('login/', LoginView.as_view(), name='login' ),
    path('logout/', logout_view, name= 'logout')
]

blog_personal/templates/_includes/_footer.html
<br>
<p>
    Derechos de autor © [2025] [Kaedev]. Todos los derechos reservados. 
</p>

blog_personal/templates/_includes/_header.html
{% load static %}

<header>

</header>

<nav>
    {% include '_includes/_menu_principal.html' %}
</nav>

blog_personal/templates/_includes/_menu_principal.html
<ul>
    <li><a href='{% url "core:home" %}'>Inicio</a></li>
    <li><a href='{% url "blog:post_list" %}'>Todos los posts</a></li>
    <li><a href='{% url "core:contact" %}'>Contacto</a></li>
    <li><a href='{% url "core:register" %}'>Registrate</a></li>

    {% if request.user.is_authenticated %}
    <li><a href='{% url "core:logout" %}'>Cerrar sesion</a></li>
    {% endif %}

    <li>
        {% if request.user.is_authenticated %}
            <p>Hola, {{ request.user }}</p>
        {% else %}
        <p><a href='{% url "core:login" %}'>Iniciar Sesión</a></p>
        {% endif %}
    </li>
</ul>